code_car:
    resource: "@CodeCarBundle/Controller/"
    type:     annotation
    prefix:   /cars

code_produto:
    resource: "@CodeProdutoBundle/Controller/"
    type:     annotation
    prefix:   /produto/

app:
    resource: @AppBundle/Controller/
    type:     annotation